### ISSUE TITLE
Error TS2304: Cannot find name 'DatePickerOptions' 

### ISSUE THREAD

**Issue by bernardomed** [bleenco/ng2-datepicker#293]
I just installed ng2-datepicker in my project and got this error when I added it.

Added `import { NgDatepickerModule } from 'ng2-datepicker';` to the app-module.

Added `import { DatepickerOptions } from 'ng2-datepicker';` to the component.

Then added this to the component as well
```
    options: DatePickerOptions = {
    format: 'DD-MM-YYYY',
    todayText: 'Oggi',
    style: 'big'
  };
```
FInally, I added it to the HTML file
```
<ng2-datepicker [options]="options" id="date_of_birth" type="date" name="date_of_birth" [(ngModel)]="date" required #name="ngModel">>
          </ng2-datepicker>
```
Am I doing something wrong here?

**Comment by bernardomed** [comment]
Found the error, lower case p in DatePickerOptions. Sorry about that.

**Comment by jkuri** [comment]
please check again with the new version 2.2.1, I just pushed to npm.

**Comment by bernardomed** [comment]
Didn't change a thing.

I uninstalled ng2-datepicker, cleaned npm cache, installed again, same error.

**Comment by luckynipun** [comment]
@bernardomed change the html tag to <ng-datepicker from <ng2-datepicker. later import the appropriate Datepickeroptions. You should be fine. The html tag was changed in the latest update.

**Comment by bernardomed** [comment]
@luckynipun The error happens even if I don't have the HTML tag.

**Comment by luckynipun** [comment]
@bernardomed Did you observe your import statement
`import { DatepickerOptions } from 'ng2-datepicker';`
where as you are declaring options in DatePickerOptions
`options: DatePickerOptions = {
    format: 'DD-MM-YYYY',
    todayText: 'Oggi',
    style: 'big'
  };`
Did you change it correctly? Is the error still there?
